### ISSUE TITLE
xDebug.

### ISSUE THREAD

**Issue by Fessan** [egal/egal-docs#44]
FROM composer:2.0 as builder
WORKDIR /app/
COPY . .
RUN composer install --optimize-autoloader --no-dev

FROM harbor.smw.tom.ru/lara-base/lara-base:Release0.0.1
#RUN /var/www/app/artisan migrate --force
RUN apk add --no-cache $PHPIZE_DEPS && pecl install xdebug-2.8.0 && docker-php-ext-enable xdebug
RUN printf 'xdebug.remote_autostart=on \nxdebug.remote_enable=on \nxdebug.remote_handler="dbgp" \nxdebug.remote_host="10.140.0.76" \nxdebug.remote_port=9001 \nxdebug.remote_mode=req \nxdebug.idekey="PHPSTORM" \nxdebug.remote_log=/tmp/xdebug.log' >> /usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini
COPY . .
ENTRYPOINT /var/www/app/artisan serve --host=0.0.0.0 --port=8000
Так сделано в АОП

**Comment by rollsover** [comment]
Отправить на проверку Соне Ч..

**Comment by rollsover** [comment]
@annstgn 🚩 2
