### ISSUE TITLE
Актуализация описания работы с функционалом "Общение между сервисами".

### ISSUE THREAD

**Issue by PolinaFarlie** [egal/egal-docs#50]
1. Разобраться с тем, нужно ли заменить в коде if ($response->hasError()) заменить на if (!empty($response->getErrorMessage)), если нужно то внести в код изменения и сказать, что заменить в доке.
2. Актуализировать код на предмет возможности разработчикам открывать/закрывать соединения. Ее не должно быть.
3. Проверить, нужен  ли параметр состояния авторизации. Если нет, сказать, чтобы убрали из доков.

**Comment by rollsover** [comment]
Поправить PR и самостоятельно слить

**Comment by annstgn** [comment]
@PolinaFarlie  :треугольный_флаг: 2
