### ISSUE TITLE
Action Create Many создает не более 9 записей.

### ISSUE THREAD

**Issue by rollsover** [egal/egal-docs#66]
- Egal Version: #.#.#
- PHP Version: #.#.#
- Database Driver & Version:
- RabbitMQ Version or Docker Image:

### Описание:

(Напишите свой ответ здесь.)

### Действия по воспроизведению:

1. 
2. 
3.

**Comment by annstgn** [comment]
Исправлена ошибка с недоступностью числа объектов, равного максимуму

**Comment by rollsover** [comment]
@annstgn 🚩 2
