### ISSUE TITLE
Фильтрация по фейковым полям.

### ISSUE THREAD

**Issue by rollsover** [egal/egal-docs#72]
### Ваше предложение связано с проблемой?

При запросе фронта на фильтрацию фейковых полей нет понятного фидбэка от системы. В метаданных фейковое поле может быть создано неправильно.

### Опишите желаемое решение

Ограничить property-type тремя типами: relation, field и fake_field. Полю всегда должен быть задан тип. При попытке задать тип иной чем один из трех перечисленных выводится ошибка: Property-type is incorrect.

### Опишите альтернативы, которые вы рассмотрели

Делать запрет на фронте на запрос на фильтрацию фейковых полей

**Comment by rollsover** [comment]
@annstgn оцени работу @PolinaFarlie

**Comment by annstgn** [comment]
@PolinaFarlie :triangular_flag_on_post: 2
