### ISSUE TITLE
fixed typo

### ISSUE THREAD

**Issue by Fessan** [egal/egal-docs#9]
https://github.com/smartworldteam/egal-docs/blob/main/server/services_communication.md
The item "Authorization service must have SERVICE_NAME = auth".
You need to change the environment variable to APP_SERVICE_NAME

**Comment by dineshkumar12004** [comment]
can i work on this issue ?
This is a documentation typo fix right ?

**Comment by Fessan** [comment]
> can i work on this issue ?
> This is a documentation typo fix right ?
